language: node_js

node_js:
  - "7"
  - "6"

services:
  - docker

before_install:
  - docker pull couchbase:community
  - travis_retry docker network create settee_net
  - docker run -d --name db --net settee_net -p 8091-8094:8091-8094 -p 11210:11210 couchbase:community
  - docker ps -a
  - sleep 10
  - travis_retry docker exec db couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-username=admin --cluster-password=secret --cluster-ramsize=768 --cluster-index-ramsize=512 --cluster-fts-ramsize=256 --index-storage-setting=default --services=data,index,query,fts
  - travis_retry docker exec db couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=testing --bucket-ramsize=768 --enable-flush=1 --bucket-replica=0 --wait -u admin -p secret
  - sleep 5
  - travis_retry docker exec db cbq --script="CREATE PRIMARY INDEX ON testing"

script: npm run test:ci

after_success:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run coverage; fi

env:
  global:
    - CLUSTER_URL: 127.0.0.1
    - BUCKET_NAME: "testing"

notifications:
  slack:
    secure: MkCKfMtPbKYgMkGA3q9GpHt90Mg0SrrKZmD7wmgYoUYaF/QvHI+I44gU2a53w7wpVKeFiJ1B0ZGf8y4B6YeS8PlnzRQA6k2HmdlJ+6prTcWCqxPXxnbR1GXp427IxeIWbgo5fNt5DcfF7XMB5MKHWU8ZA/0dWkK/d5DyaSRn7kshIe1n9N804pIWmUjTW0teX9c4xrdoqGeJbwR74hsgEAkQpZ04ZtWR+tNmpXgfNKgqfleSG2FhD/fCXck2xYfWiac9sApaP3sDsOXQQDd/sAfGm5qGEpreE/g2WxlVprzT86JTH+hnT/BVPQq5yuQxViP8pypHQ1SCqQwJoT47Pi2HXZim8Pflu+gYMmtmIExudl7m7dtUyJx51GIV9d282BJIPXs/rI69HjW32Blb4iyrqwsqHbU096GnICXPTKBvD3TP2lp5Ke6s7qHfAZS4mTkZUCjb9U5avY8bhBzEqmdP48A7DoTqAfShmtIjMQCP8E3DKUd59VpJwsvxumBB/TcqCLVZa3HF8iCRpmrIf2UBkXbK/YfozQG+sBkhcr02pSeFCnPqCF1I1mlmFlDv+fV7STkLQpHbiMHcH4qiMejoyfK+U9lza7A489TFl8+ah0ZShMzmW33otJtzACKwWCvIvJNPKLzvEeHvHnDIeXxSMZkIv6TLRIuCNNGrNKQ=

